### ISSUE TITLE
Function Request: Add reset button position on case

### ISSUE THREAD

**Issue by TonyWu20** [yejianfengblue/dactyl-generator-demo#2]
It will be greatly helpful if the generator can provide an option for reset buttons

**Comment by yejianfengblue** [comment]
This project [dactyl generator demo](https://github.com/yejianfengblue/dactyl-generator-demo), created by me, just show the parameter meaning. The [dactyl generator](https://dactyl.siskam.link/) is created by [Ibnu Daru Aji](https://github.com/ibnuda/dactyl-keyboard). 

Actually qmk has the `reset` key under Quantum tab
![qmk-reset](https://user-images.githubusercontent.com/28599139/137660290-8512c826-e9ac-4811-bce8-534026d813b7.png)
