### ISSUE TITLE
Site is down

### ISSUE THREAD

**Issue by ayroblu** [yejianfengblue/dactyl-generator-demo#3]
Hi I saw that https://dactyl.siskam.link is down, are you planning on keeping it up? Or perhaps is there a way to run this locally?

**Comment by yejianfengblue** [comment]
Follow [this guide](https://github.com/ibnuda/dactyl-keyboard#development) to run the website locally. And [create an issue in ibnuda's repository](https://github.com/ibnuda/dactyl-keyboard/issues) to report the website down issue.
